# Generated by Django 2.0.5 on 2018-05-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=8)),
                ('registration_date', models.DateField(auto_now=True)),
                ('validity_date', models.DateField()),
                ('validity_count', models.IntegerField(default=0)),
                ('unlimited_count', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=2)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=16)),
                ('belt', models.CharField(choices=[('-10', '10th Gup White Belt 十级白带'), ('-9', '9th Gup White Belt With Yellow Stripe 九级白黄带'), ('-8', '8th Gup Yellow Belt 八级黄带'), ('-7', '7th Gup Yellow Belt With Green Stripe 七级黄绿带'), ('-6', '6th Gup Green Belt 六级绿带'), ('-5', '5th Gup Green Belt With Blue Stripe 五级绿蓝带'), ('-4', '4th Gup Blue Belt 四级蓝带'), ('-3', '3rd Gup Blue Belt With Red Stripe 三级蓝红带'), ('-2', '2nd Gup Red Belt 二级红带'), ('-1', '1st Gup Red Belt With Black Stripe 一级红黑带'), ('1', '1st Dan (Il Dan) Black Belt 黑带一段'), ('2', '2nd Dan (Ee Dan) Black Belt 黑带二段'), ('3', '3rd Dan (Sam Dan) Black Belt 黑带三段'), ('4', '4th Dan (Sa Dan) Black Belt 黑带四段'), ('5', '5th Dan (Oh Dan) Black Belt 黑带五段'), ('6', '6th Dan (Yook Dan) Black Belt 黑带六段'), ('7', '7th Dan (Chil Dan) Black Belt 黑带七段'), ('8', '8th Dan (Pal Dan) Black Belt 黑带八段'), ('9', '9th Dan (Koo Dan) Black Belt 黑带九段')], default=None, max_length=4)),
                ('password', models.CharField(default=None, max_length=32)),
                ('gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Gym')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(auto_now=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Member')),
                ('training_gym', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Gym')),
            ],
        ),
    ]
